### ISSUE TITLE
Weird column in tab bar

### ISSUE THREAD

**Issue by Momen-MKadry** [ImMainTheme/ArchyVivaldi#1]
Hey, I had used this CSS for some time and it worked fine really, thanks for your effort, however I had my config files deleted recently and vivaldi's file too, I installed this again followed all the steps and now I have this weird column in the tab bar

![image](https://github.com/ImMainTheme/ArchyVivaldi/assets/93672218/4d79f8a8-9be0-4c94-b4f2-753afe1e7769)
What can be the cause for that?

**Comment by ImMainTheme** [comment]
Hi,
I have updated a fix for this issue, please download the latest css file to check if this issue persist

**Comment by Momen-MKadry** [comment]
Sorry for the late reply I was away from my laptop,
Yes it is fixed now thanks a lot
