### ISSUE TITLE
The new tab button is located above the separator when 14 or more tabs are open. Not displaying the title "New Tab" in all scenarios

### ISSUE THREAD

**Issue by R0STEFAN** [ImMainTheme/ArchyVivaldi#5]
The new tab button is located above the separator when 14 or more tabs are open. Not displaying the title "New Tab" in all scenarios. how to make the "New tab" button be located below the separator under pinned tabs and to se title " New tab"? See attached screenshot.
![Знімок екрана 2024-08-27 113831](https://github.com/user-attachments/assets/2b21b859-9904-4139-a816-1dbc9e1c638c)

**Comment by R0STEFAN** [comment]
I solved the issue with the Name "New Tab" The problem was in the system language. My language is Ukrainian. I adjusted the code to the Ukrainian name of the button and the name "New tab" was added.

**Comment by R0STEFAN** [comment]
A bug with a button that moves above the separator if more than 14 tabs remain open. I am attaching 2 screenshots. The first one has 13 tabs open. On the second, 14 tabs are open
![Знімок екрана 2024-08-27 132410](https://github.com/user-attachments/assets/5c9a3582-1b1e-4fb8-a623-53cabcdf354b)
![Знімок екрана 2024-08-27 132452](https://github.com/user-attachments/assets/c3e058ba-7433-4131-94d4-3127598f4cc8)

**Comment by ImMainTheme** [comment]
Try adding this see if this solve your problem.
"New Tab" I will fix it to fit all language in next updates.
Thanks for your feedback!

```
.resize:has(.separator):has(.sync-and-trash-container .newtab) {
	.separator {translate: 0 calc(var(--biggertab) * -1);}
	.newtab  {translate: 0 18px;}
}
```

**Comment by R0STEFAN** [comment]
> Try adding this see if this solve your problem. "New Tab" I will fix it to fit all language in next updates. Thanks for your feedback!
> 
> ```
> .resize:has(.separator):has(.sync-and-trash-container .newtab) {
> 	.separator {translate: 0 calc(var(--biggertab) * -1);}
> 	.newtab  {translate: 0 18px;}
> }
> ```

That's how it works. But there are small inaccuracies. There is a displacement of the "New tab" button. See 2 screenshots. The first has 13 tabs, the second has 14 tabs
![Знімок екрана 2024-08-28 093935](https://github.com/user-attachments/assets/fba34bc6-5717-4041-83ca-7c5dda417728)
![Знімок екрана 2024-08-28 093944](https://github.com/user-attachments/assets/3c349504-d684-49d0-a608-d900aa247f57)

**Comment by ImMainTheme** [comment]
This one should fix the issue.👍

`.sync-and-trash-container {margin: 0 !important;}`

**Comment by R0STEFAN** [comment]
> This one should fix the issue.👍
> 
> `.sync-and-trash-container {margin: 0 !important;}`

This solution not working

**Comment by ImMainTheme** [comment]
I have rewrite some code on latest version.
Please give the  latest one a try and see if it works fine on your end.

**Comment by R0STEFAN** [comment]
> I have rewrite some code on latest version.
> Please give the latest one a try and see if it works fine on your end.
I tried. works much better now. Thank you
